name: Tests

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Install dependencies"
      run: sudo apt-get install -y build-essential gfortran liblapack-dev libblas-dev openmpi-bin openmpi-common libopenmpi-dev cmake
    - name: Build GRASP
      run: |
        ./configure.sh
        cd build/
        make
        make install
    - name: Verify binaries
      run: ./contrib/checkbin.sh
    - name: Run test suite
      run: cd build/ && ctest
